### ISSUE TITLE
generate project file that has handled all dependencies 

### ISSUE THREAD

**Issue by lewis081** [BobBuildTool/bob-tutorials#5]
Dear Author:
     　　I try to use `bob project` to generate .pro file that can manage the dependencies of project. However, i failed.
     　　Do you have way to export one recipe to visual project that include its all dependencies' source code. 
     　　Right now , i need handle this manually by using some shell command such as `cp src dst`. It is very cumbersome.I think that it's better to handle these automatically.
     　　BTW, i am not familiar with CMake. Can i use CMake to generate some kind of project file that has handled all dependencies?
     　　Thank you for your reply.

**Comment by jkloetzke** [comment]
Did you use one of the existing project generators (Eclipse, Qt Creator)? They should automatically add all the involved sources of the package and its dependencies to the project. Sources of other packages are not included into the project.

CMake can also create project files for some IDEs (see `cmake -G` or cmake-generators(7)) but this will be limited to one recipe/package only. The `bob project` command can generate project files that span a recipe and its dependencies.

**Comment by lewis081** [comment]
I am so happy that the export project(maybe for Qt Creator) can handle dependencies automatically.     
 QT CREATOR is my ide right now. 
I follow this command `$ bob project <genericArgs> <generator> <package> <specificArgs>` .
My situation as follows:
`bob project -n qt-creator vexpress/initramfs/busybox/ --kit Desktop`

![image](https://user-images.githubusercontent.com/5345837/35267851-8e237532-0062-11e8-81fd-8da277f8c221.png)
But i can not find the .pro file that qtcreator can open.
Actually, I don't know how to specify parameter --kit. I didn't use sdktool command like tutorial.  
Could you give me some tips to generate .pro file?

**Comment by rhubert** [comment]
Well, you do not need a `.pro` file. Just use the `*.creator` file. 
With 
```
bob project -n qt-creator vexpress/initramfs/busybox/
```
you're creating a qt-creator project for the busybox package and all it's dependencies (but there aren't any). Since there are no dependencies for busybox you'll only get busybox sources as well as some build options. 

For the whole project do
```
bob project qt-creator vexpress
```
And start qt-creator:
```
qtcreator projects/vexpress/
```

Regarding the kit: QtCreator creates a Desktop kit on the first startup. This can be used for host-projects. QtCreator will pick up your host toolchain and setup all the directories and compiler path, debugger,...
If you're crosscompiling you'll want to setup a kit pointing to your crosscompiler SDK. This will enable QtCreator to use the compilers build-in defines and so on.
There is some documentation about how to setup a kit: http://bob-build-tool.readthedocs.io/en/latest/tutorial/compile.html#qtcreator Please feel free the extend this and create a PR.
If I remember correctly it's also possible to create a kit using the GUI and give only the name to bob's qt-creator project. Some more informations can be found in the official  qt-creator help http://doc.qt.io/qtcreator/creator-targets.html

**Comment by lewis081** [comment]
Sorry about reply too late.

It works when I type command as follows.
`bob project qt-creator vexpress --kit Desktop`
It generated errors when i didn't use `--kit Desktop`
I open the generated files with qt-creator. And the dependencies are in the projects. 
Here is the pic:

![image](https://user-images.githubusercontent.com/5345837/35606237-e1751246-0688-11e8-9682-de4769e51975.png)




Thank  you very much.

**Comment by jkloetzke** [comment]
I guess you had more than one profile with `Desktop` in the name. Anyway, glad to see that it worked...
